CREATE USER ASP_ELASTICDB WITH PASSWORD='bJT!n*9qyNDH~ybhSp'
GO
ALTER ROLE [db_owner] ADD MEMBER ASP_ELASTICDB


REVOKE CONNECT FROM BLSRW
REVOKE CONNECT FROM BLSRO
REVOKE CONNECT FROM BLS_ADMIN

GRANT CONNECT TO BLSRW
GRANT CONNECT TO BLSRO
GRANT CONNECT TO BLS_ADMIN